package vn.edu.quiz.auth.controller;

import com.fasterxml.jackson.databind.*;
import java.net.*;
import java.net.http.*;
import java.time.Duration;
import java.util.*;
import java.util.concurrent.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.test.context.ActiveProfiles;
import vn.edu.quiz.auth.security.AuthSessionRegistry;
import static org.assertj.core.api.Assertions.*;

/** Real HTTP + WebSocket + MySQL. CookieManager simulates browser session-cookie transport. */
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT, properties = {
    "spring.datasource.url=jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/quizz_task2_test?connectionTimeZone=UTC&connectTimeout=3000&socketTimeout=3000",
    "server.servlet.session.timeout=5s"
})
@ActiveProfiles("mysql")
class AuthNetworkIT {
    @LocalServerPort int port;
    @Autowired JdbcTemplate jdbc;
    @Autowired ObjectMapper json;
    @Autowired PasswordEncoder passwords;
    @Autowired AuthSessionRegistry registry;
    final List<String> createdUsers = new ArrayList<>();
    final List<Client> clients = new ArrayList<>();
    final List<WebSocket> sockets = new ArrayList<>();
    static final String PASSWORD = "Test-password-42";
    class Client {
        final CookieManager cookies = new CookieManager(null, CookiePolicy.ACCEPT_ALL);
        final HttpClient http = HttpClient.newBuilder().cookieHandler(cookies).connectTimeout(Duration.ofSeconds(3)).build();
        String token;
        String sessionId() {
            return cookies.getCookieStore().getCookies().stream().filter(c -> c.getName().equals("JSESSIONID"))
                    .map(HttpCookie::getValue).findFirst().orElse(null);
        }
        HttpResponse<String> get(String path) throws Exception { return request("GET", path, null, false); }
        HttpResponse<String> request(String method, String path, Object body, boolean csrf) throws Exception {
            var builder = HttpRequest.newBuilder(URI.create("http://127.0.0.1:" + port + path)).timeout(Duration.ofSeconds(5));
            if (csrf && token != null) builder.header("X-CSRF-TOKEN", token);
            if (body != null) builder.header("Content-Type", "application/json");
            return http.send(builder.method(method, body == null ? HttpRequest.BodyPublishers.noBody()
                    : HttpRequest.BodyPublishers.ofString(json.writeValueAsString(body))).build(), HttpResponse.BodyHandlers.ofString());
        }
        void csrf() throws Exception { var response = get("/api/auth/csrf"); assertThat(response.statusCode()).isEqualTo(200); token = json.readTree(response.body()).get("token").asText(); }
    }
    Client client() { var client = new Client(); clients.add(client); return client; }
    String username() { return "auth_" + UUID.randomUUID().toString().replace("-", "").substring(0, 15); }
    long register(Client client, String name) throws Exception {
        createdUsers.add(name.toLowerCase(Locale.ROOT));
        var response = client.request("POST", "/api/auth/register", Map.of("username", name, "displayName", " Test User ", "password", PASSWORD), true);
        assertThat(response.statusCode()).as(response.body()).isEqualTo(201);
        assertThat(response.body()).doesNotContain("password", "hash", PASSWORD);
        assertThat(response.headers().firstValue("Cache-Control")).contains("no-store");
        assertThat(json.readTree(response.body()).get("displayName").asText()).isEqualTo("Test User");
        return json.readTree(response.body()).get("id").asLong();
    }
    Client loggedIn() throws Exception {
        Client client = client(); client.csrf(); String name = username(); register(client, name);
        var response = client.request("POST", "/api/auth/login", Map.of("username", name, "password", PASSWORD), true);
        assertThat(response.statusCode()).as(response.body()).isEqualTo(200); client.csrf(); return client;
    }
    @AfterEach void cleanup() {
        for (Client client : clients) if (client.sessionId() != null) registry.revoke(client.sessionId(), "LOGGED_OUT");
        sockets.forEach(WebSocket::abort);
        // Only usernames generated by this test, not unrelated accounts or schema history.
        for (String username : createdUsers) jdbc.update("DELETE FROM app_user WHERE username = ?", username);
        clients.forEach(c -> c.http.close());
    }
    @Test void registerHashLoginSessionRotationIdentityAndLogout() throws Exception {
        Client client = client(); client.csrf(); String anonymousSession = client.sessionId(); String oldToken = client.token;
        String name = username(); long userId = register(client, name.toUpperCase(Locale.ROOT));
        assertThat(jdbc.queryForObject("SELECT DATABASE()", String.class)).isEqualTo("quizz_task2_test");
        String hash = jdbc.queryForObject("SELECT password_hash FROM app_user WHERE id=?", String.class, userId);
        assertThat(hash).isNotEqualTo(PASSWORD).startsWith("$2a$10$"); assertThat(passwords.matches(PASSWORD, hash)).isTrue();
        assertThat(client.get("/api/auth/me").statusCode()).isEqualTo(401); // Register does not log in.
        var response = client.request("POST", "/api/auth/login", Map.of("username", name, "password", PASSWORD, "userId", 999999), true);
        assertThat(response.statusCode()).as(response.body()).isEqualTo(200);
        assertThat(json.readTree(response.body()).get("id").asLong()).isEqualTo(userId);
        assertThat(client.sessionId()).isNotEqualTo(anonymousSession);
        assertThat(response.headers().allValues("Set-Cookie").toString()).contains("HttpOnly", "SameSite=Lax");
        Client stale = client(); stale.cookies.getCookieStore().add(URI.create("http://127.0.0.1:" + port), new HttpCookie("JSESSIONID", anonymousSession));
        assertThat(stale.get("/api/auth/me").statusCode()).isEqualTo(401);
        client.token = oldToken;
        assertError(client.request("POST", "/api/auth/logout", null, true), 403, "CSRF_INVALID");
        client.csrf();
        assertError(client.request("POST", "/api/auth/login", Map.of("username", name, "password", PASSWORD), true), 409, "ALREADY_AUTHENTICATED");
        assertThat(json.readTree(client.get("/api/auth/me").body()).get("id").asLong()).isEqualTo(userId);
        String authenticatedSession = client.sessionId();
        assertThat(client.request("POST", "/api/auth/logout", null, true).statusCode()).isEqualTo(204);
        assertThat(client.get("/api/auth/me").statusCode()).isEqualTo(401);
        Client replay = client(); replay.cookies.getCookieStore().add(URI.create("http://127.0.0.1:" + port), new HttpCookie("JSESSIONID", authenticatedSession));
        assertThat(replay.get("/api/auth/me").statusCode()).isEqualTo(401);
    }
    @Test void invalidCredentialsDeletedAccountDuplicatesAndValidation() throws Exception {
        Client client = client(); client.csrf(); String name = username(); long id = register(client, name);
        assertError(client.request("POST", "/api/auth/register", Map.of("username", name.toUpperCase(Locale.ROOT), "displayName", "Other", "password", PASSWORD), true), 409, "USERNAME_TAKEN");
        for (String username : List.of(name, "missing_account")) {
            assertError(client.request("POST", "/api/auth/login", Map.of("username", username, "password", "incorrect-password"), true), 401, "INVALID_CREDENTIALS");
        }
        jdbc.update("UPDATE app_user SET deleted_at_ms=? WHERE id=?", System.currentTimeMillis(), id);
        assertError(client.request("POST", "/api/auth/login", Map.of("username", name, "password", PASSWORD), true), 401, "INVALID_CREDENTIALS");
        assertError(client.request("POST", "/api/auth/register", Map.of("username", "bad name", "displayName", "D", "password", "short"), true), 400, "INVALID_REQUEST");
        assertError(client.request("POST", "/api/auth/register", Map.of("username", "valid_name", "displayName", "D", "password", "é".repeat(40)), true), 400, "INVALID_REQUEST");
        assertError(client.request("POST", "/api/auth/login", Map.of("username", name, "password", PASSWORD), false), 403, "CSRF_INVALID");
    }
    @Test void unauthenticatedOrForgedAccountCannotConnect() throws Exception {
        Client client = client();
        assertError(client.get("/api/auth/me"), 401, "UNAUTHENTICATED");
        deniedSocket(client, "http://localhost:8080", "", 401);
        client.cookies.getCookieStore().add(URI.create("http://127.0.0.1:" + port), new HttpCookie("JSESSIONID", "forged-user-1"));
        deniedSocket(client, "http://localhost:8080", "", 401);
        var basic = HttpRequest.newBuilder(URI.create("http://127.0.0.1:" + port + "/api/auth/me"))
                .header("Authorization", "Basic ZmFrZTpmYWtl").GET().build();
        assertThat(client.http.send(basic, HttpResponse.BodyHandlers.ofString()).statusCode()).isEqualTo(401);
    }
    @Test void browserCookieSocketOriginIdentityReplacementAndLogoutCloseCurrentSocket() throws Exception {
        Client client = loggedIn();
        long id = json.readTree(client.get("/api/auth/me").body()).get("id").asLong();
        deniedSocket(client, "http://evil.invalid", "", 403);
        deniedSocket(client, null, "", 403);
        deniedSocket(client, "http://localhost:8080", "?userId=999", 400);
        var first = new Listener(); var second = new Listener();
        socket(client, "http://localhost:8080", "", first); socket(client, "http://localhost:8080", "", second);
        for (Listener listener : List.of(first, second)) {
            JsonNode event = json.readTree(listener.messages.poll(3, TimeUnit.SECONDS));
            assertThat(event.get("type").asText()).isEqualTo("AUTH_READY");
            assertThat(event.get("payload").get("userId").asLong()).isEqualTo(id);
            assertThat(event.toString()).doesNotContain("password", "hash");
        }
        client.csrf();
        assertThat(client.request("POST", "/api/auth/logout", null, true).statusCode()).isEqualTo(204);
        JsonNode replaced=json.readTree(first.messages.poll(3,TimeUnit.SECONDS));
        assertThat(replaced.path("type").asText()).isEqualTo("SESSION_REPLACED");
        assertThat(replaced.path("payload").path("replacementGeneration").asLong()).isGreaterThan(replaced.path("payload").path("connectionGeneration").asLong());
        assertThat(first.closed.get(3, TimeUnit.SECONDS)).isEqualTo(4002);
        assertThat(second.closed.get(3, TimeUnit.SECONDS)).isEqualTo(4001);
        assertThat(first.reason).isEqualTo("SESSION_REPLACED");
        assertThat(second.reason).isEqualTo("LOGGED_OUT");
        deniedSocket(client, "http://localhost:8080", "", 401);
    }
    @Test void identityInUnsupportedMessageIsNeverTrusted() throws Exception {
        Client client = loggedIn(); Listener listener = new Listener();
        WebSocket socket = socket(client, "http://localhost:8080", "", listener);
        assertThat(listener.messages.poll(3, TimeUnit.SECONDS)).contains("AUTH_READY");
        socket.sendText("{\"kind\":\"COMMAND\",\"type\":\"FUTURE_COMMAND\",\"userId\":999999}", true).join();
        assertThat(listener.closed.get(3, TimeUnit.SECONDS)).isEqualTo(1008);
        assertThat(listener.reason).isEqualTo("UNSUPPORTED_MESSAGE");
        assertThat(client.get("/api/auth/me").statusCode()).isEqualTo(200);
    }
    @Test void idleSessionExpiresAndClosesExistingSocket() throws Exception {
        Client client = loggedIn(); Listener listener = new Listener();
        socket(client, "http://localhost:8080", "", listener);
        assertThat(listener.messages.poll(3, TimeUnit.SECONDS)).contains("AUTH_READY");
        assertThat(listener.closed.get(9, TimeUnit.SECONDS)).isEqualTo(4001);
        assertThat(listener.reason).isEqualTo("SESSION_EXPIRED");
        assertThat(client.get("/api/auth/me").statusCode()).isEqualTo(401);
        deniedSocket(client, "http://localhost:8080", "", 401);
    }
    WebSocket socket(Client client, String origin, String query, Listener listener) throws Exception {
        var builder = client.http.newWebSocketBuilder().connectTimeout(Duration.ofSeconds(3));
        if (origin != null) builder.header("Origin", origin);
        WebSocket socket = builder.buildAsync(URI.create("ws://127.0.0.1:" + port + "/ws" + query), listener).get(5, TimeUnit.SECONDS);
        sockets.add(socket); return socket;
    }
    void deniedSocket(Client client, String origin, String query, int status) {
        assertThatThrownBy(() -> socket(client, origin, query, new Listener())).isInstanceOfSatisfying(ExecutionException.class, error -> {
            assertThat(error.getCause()).isInstanceOfSatisfying(WebSocketHandshakeException.class,
                    handshake -> assertThat(handshake.getResponse().statusCode()).isEqualTo(status));
        });
    }
    void assertError(HttpResponse<String> response, int status, String code) throws Exception {
        assertThat(response.statusCode()).as(response.body()).isEqualTo(status);
        assertThat(json.readTree(response.body()).get("code").asText()).isEqualTo(code);
        assertThat(response.body()).doesNotContain(PASSWORD, "password_hash", "jdbc:");
    }
    static class Listener implements WebSocket.Listener {
        final BlockingQueue<String> messages = new LinkedBlockingQueue<>();
        final CompletableFuture<Integer> closed = new CompletableFuture<>();
        final StringBuilder fragments = new StringBuilder();
        volatile String reason;
        @Override public void onOpen(WebSocket socket) { socket.request(1); }
        @Override public CompletionStage<?> onText(WebSocket socket, CharSequence data, boolean last) {
            fragments.append(data); if (last) { messages.add(fragments.toString()); fragments.setLength(0); }
            socket.request(1); return null;
        }
        @Override public CompletionStage<?> onClose(WebSocket socket, int code, String reason) {
            this.reason = reason; closed.complete(code); return null;
        }
        @Override public void onError(WebSocket socket, Throwable error) { closed.completeExceptionally(error); }
    }
}
